### ISSUE TITLE
to discuss with the team -> what is the true price of ETH

### ISSUE THREAD

**Issue by juanpablovs** [oceanprotocol/predict-eth#18]
May be we should discuss (all the members of the team) and reach an agreement on the true price of ETH. Specifically:
1. Why do we consider that the true price of ETH (an easy one when talking about transactions per block)
2. How will it be measured
3. Where it is obtained

Some examples:
1. We consider the true price of ETH the price that is the median of all approved transactions in any given block
2. We consider the true price of ETH the weighted average of the price and the size of the approved transaction of a block
3. We consider the true price of ETH the median of the transactions that happen exclusively between ETH and a stable coin in any given block

**Comment by trentmc** [comment]
There's not such thing as "true" price.

There's only: "what's actionable to make $". That's all that matters.

E.g. in arb trading, if the price on exchange A < on exchange B, then you buy on A and sell on B, and make $$. These differences are where the opportunity lies.

E.g. in hedge funds, quants compute a "fair market value", then see if there are derivatives that give price exposure higher or lower, which eventually revert to "fair market value" due to the nature of the asset (warrant, convertible bond, etc). One could argue that "fair market value" is "true price" but "true" has huge ontological baggage. Much simpler to focus on specific tangible benefits.

In predict-eth contest, we are using Binance price, on purpose, as the target. It's not some general vague idea of ETH price, it's a very specific thing.

I recommend that we keep doing that.

**Comment by juanpablovs** [comment]
ok, thank you for the explanation

Just one question regarding this:

Binance is a private exchange with a private (and fairly controversial) order book. All the sources of data that we are using for the contest so far come from DEXes.

Do we proceed just as it is?

**Comment by trentmc** [comment]
We will have data from both CEXes and DEXes.

One of the issues that you're working on is getting data from TheGraph, from which you'd be getting historical dex data.

**Comment by juanpablovs** [comment]
I'll take that as a yes then, thank you

**Comment by trentmc** [comment]
What more do we need to be able to close this issue?

**Comment by juanpablovs** [comment]
I am ok with what you have explained

**Comment by trentmc** [comment]
Great! Then since you opened the issue, it's best that you close it.
