### ISSUE TITLE
BTC asset in example can not be downloaded

### ISSUE THREAD

**Issue by jfdelgad** [oceanprotocol/predict-eth#53]
The BCT example contains an asset that is not public and returns `Not allowed` if the user tries to download it.
https://github.com/oceanprotocol/predict-eth/blob/main/examples/get-btcdata-ocean-binance.md

**Comment by trentmc** [comment]
Is someone working to solve this? @jfdelgad or @juanpablovs ?

**Comment by juanpablovs** [comment]
I just tested it. I requested a download 3 times. 2 times downloaded without a problem, one time (the second) threw an error, it's not the asset, it's related to the market, may be @mihaisc  can help us out?

**Comment by trentmc** [comment]
One possible issue: 
- does it have a dispenser created for it? 
  - If no, ocean.py [dispenser README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/dispenser-flow.md) shows how
  - This ultimately leads to a call to [ERC20Template.sol::createDispenser()](https://github.com/oceanprotocol/contracts/blob/7e7ae3f68be76e90a9474a2a8499fd69c89ea28b/contracts/templates/ERC20Template.sol#L409). 
- Also critical: when the dispenser was created, the argument `allowedSwapper` (final arg) needs to be set to `0`, otherwise only the publisher can dispense. (Yes this is a silly quirk. But once you know about it, just use it in your code:)
